MyBuild/urls.py
from django.contrib import admin
from django.urls import path, include

from account import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('add_user/', views.AddUserView.as_view(), name='add_user'),
    path('admin_app/', include('admin_app.urls')),
    path('employee_app/', include('employee_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee_app/urls.py
from django.contrib import admin
from django.urls import path

from employee_app import views

urlpatterns = [
    path('main_employee/', views.MainEmployeeView.as_view(), name='main_employee'),
    path('main_employee/update/', views.AddMainUpdateView.as_view(), name='add_update'),
    path('budowa/', views.Lista_Budowa.as_view(), name='budowy'),
    path('budowa/<int:id>', views.BudowaView.as_view(), name='budowa_details'),
    path('budowa/<int:id>/add_update/', views.AddUpdateView.as_view(), name='add_updates_em'),

]

admin_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import datetime, date

wydatki = (
    (1, 'MATERIAŁY'),
    (2, 'NARZĘDZIA'),
    (3, 'PENSJE'),
    (4, 'PODWYKONAWCA'),
    (5, 'ODPADY'),
    (6, 'INNE')
)


class Budowa(models.Model):
    miasto = models.CharField(max_length=128)
    ulica = models.CharField(max_length=128)
    kod_pocztowy = models.CharField(max_length=7)
    typ = models.CharField(max_length=128)
    podwykonawca = models.CharField(max_length=128)
    kierownik = models.ForeignKey(User, on_delete=models.CASCADE, related_name='kierownik')
    budzet = models.PositiveIntegerField(default=0)
    users = models.ManyToManyField(User)
    image = models.ImageField(null=True, blank=True, upload_to="images/")

    def get_absolute_url(self):
        return reverse('update_budowa', args=(self.id,))

    def __str__(self):
        return f"{self.miasto} {self.ulica}"


class Tag(models.Model):
    tag = models.CharField(max_length=64)
    def __str__(self):
        return f"{self.tag}"

class Przetarg(models.Model):
    miasto = models.CharField("MIASTO",max_length=128)
    ulica = models.CharField("ULICA", max_length=128)
    kod_pocztowy = models.CharField("KOD POCZTOWY", max_length=128)
    typ_budowy = models.CharField("TYP BUDOWLI", max_length=128)
    typ_budynku = models.CharField("TYP BUDYNKU", max_length=128)
    zleceniodawca = models.CharField("ZLECENIODAWCA", max_length=128)
    budzet = models.PositiveIntegerField("BUDŻET", default=None)
    data = models.DateField("DATA", auto_now_add=False, auto_now=False, blank=True, null=True)
    dodanie = models.DateField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, blank=True)


    def get_absolute_url(self):
        return reverse('update_przetarg', args=(self.id, ))


class MainUpdate(models.Model):
    text = models.CharField(max_length=256)
    data = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class BudowaUpdate(models.Model):
    text = models.CharField(max_length=256)
    data = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    budowa = models.ForeignKey(Budowa, on_delete=models.CASCADE)


class Wydatki(models.Model):
    kategoria = models.IntegerField(choices=wydatki, default=0)
    kwota = models.PositiveIntegerField(default=None)
    budowa = models.ForeignKey(Budowa, on_delete=models.CASCADE)
    datetime = models.DateTimeField(auto_now_add=True)
    opis = models.CharField(max_length=256)

employee_app/models.py
from django.db import models

# Create your models here.

employee_app/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from admin_app.models import Budowa, BudowaUpdate, MainUpdate


class MainEmployeeView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'employee_app/base.html',{'update': MainUpdate.objects.all().order_by('data')})


class Lista_Budowa(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        budowy = Budowa.objects.filter(kierownik_id=user)
        return render(request, 'employee_app/lista_budowa.html', {'budowy': budowy})


class BudowaView(LoginRequiredMixin, View):
    def get(self, request, id):
        return render(request, 'employee_app/budowa.html', {'budowa': Budowa.objects.get(pk=id)})

class AddUpdateView(LoginRequiredMixin, View):
    def get(self, reqeust, id):
        return render(reqeust, 'admin_app/updaty/add_update.html', {'budowa': Budowa.objects.get(pk=id)})

    def post(self, request, id):
        budowa = Budowa.objects.get(pk=id)
        user = request.user
        data = datetime.now().time
        text = request.POST['text']
        BudowaUpdate.objects.create(budowa=budowa, user=user, data=data, text=text)
        return redirect('budowa_details', id)

class AddMainUpdateView(LoginRequiredMixin, View):
    def get(self, reqeust):
        return render(reqeust, 'admin_app/updaty/add_update.html')

    def post(self, request):
        user = request.user
        data = datetime.now().time
        text = request.POST['text']
        MainUpdate.objects.create(user=user, data=data, text=text)
        return redirect('main_employee')

employee_app/templates/employee_app/base.html
{% load static %}
{% include 'employee_app/employee_header.html' %}
<body>
<link rel="stylesheet" type="text/css" href="{% static '/employee_app/updaty.css' %}">
<div class="ak">AKUTALNOŚCI</div>
<div class="updates">
    {% for u in update %}
        <div class="tekst"><p>{{ u.text }}</p></div>
        <div class="autor"><p>{{ u.user }}</p></div>
        <div class="data">{{ u.data }}</div>
    {% endfor %}
</div>
<form action="{% url 'add_update' %}" method="post">
    {% csrf_token %}
    <input class="dodawnanie" type="text" name="text" placeholder="Napisz post">
    <input class="add_button" type="submit" value="DODAJ"></form>
</body>

employee_app/templates/employee_app/budowa.html
{% include 'employee_app/employee_header.html' %}
{% block zawartosc %}
{% include 'employee_app/budowa_details.html' %}
{% endblock %}

employee_app/templates/employee_app/budowa_details.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/employee_app/budowa.css' %}">
<div class="ramka">
    <div class="info">
    <h3>Miasto: {{ budowa.miasto}}</h3>
    <h3>Ulica: {{ budowa.ulica }}</h3>
    <h3>Kod pocztowy: {{ budowa.kod_pocztowy }}</h3>
    <h3>Typ budynku: {{ budowa.typ }}</h3>
    <h3>Budżet budowli: {{ budowa.budzet }}</h3>
    <h3>Podwykonawca: {{ budowa.podwykonawca }}</h3>
    <h3>Kierownik budowy: {{ budowa.kierownik }}</h3>
    </div>
</div>
<div class="updates_budowa">

        {% for update in budowa.budowaupdate_set.all %}
            <p class="autor">{{ update.user }}<p>
            <p class="tekst"> {{ update.text }}</p>
            <p class="data">{{ update.data }}</p>
        {% endfor %}
</div>
    <ul>

    <form action="{% url 'add_updates_em' budowa.id %}" method="post">
    {% csrf_token %}
    <input class="add_post" type="text" name="text" placeholder="Napisz post">
    <input class="add_b" type="submit">
</form>


    {% if budowa.image %}
        <img src="{{ budowa.image.url }}">
    {% endif %}

employee_app/templates/employee_app/employee_header.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/employee_app/nav.css' %}">
<div class="nav_background">
    <body class="body">
    <header>
        <div class="li">
            <nav>
                <ul class="nav_links">
                    <li><a class="aa" href="{% url 'main_employee' %}">STRONA GŁÓWNA</a></li>
                    <li><a class="a" href="{% url 'budowy' %}">LISTA BUDÓW</a></li>
                </ul>
            </nav>
        </div>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">
                <button>WYLOGUJ</button>
            </a>
        {% endif %}
    </header>
    </body>
</div>

employee_app/templates/employee_app/lista_budowa.html
{% include 'employee_app/employee_header.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/employee_app/lista_budow.css' %}">
{% block content %}
    <div class="head"><h1>Budowy:</h1></div>
    <table class="table">
    {% for b in budowy %}
        <tr class="trr">
            <td class="title">{{ b.miasto }} {{ b.ulica }}</td>
            <td><a class="link" href="{% url 'budowa_details' b.id %}">Pokaz szczegóły</a></td></tr>
    {% endfor %}
    </table>
{% endblock %}